# Site settings
title: Alexander Mera - Blog sobre desarrollo de software Java, Scala, Programación Funcional
email: alxmera@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Guías, explicaciones, ejemplos y opiniones relacionados con el
  desarrollo de software: java, spring framework, programación funcional y scala
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.alexmera.com" # the base hostname & protocol for your site
twitter_username: alexmera
github_username:  alexmera

# Build settings
markdown: kramdown

# Outputting
permalink:     pretty
paginate_path: /page:num
timezone:      America/Bogota

#Exclude
exclude: [README.md, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, bower_components, bower.json]

# Markdown Processors
kramdown:
    input: GFM